env:
  browser: true
  es2021: true
#extends: 'eslint:recommended'
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - coffeescript
  - import
globals:
  __DEV__: true
  DEBUG: true
  require: true
  __useCssModules__: true
  process: true
rules:
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
settings:
  import/resolver: webpack
